### ISSUE TITLE
OOV handling and BLEU

### ISSUE THREAD

**Issue by yashugupta786** [VasudevGupta7/seq2seq#1]
Hi 
Your implementation for transformer is very good . whats the Bleu score you are getting for this data set. Also are you handling the OOV words in the prediction.

**Comment by thevasudevgupta** [comment]
Hi,
sorry I missed this earlier. I was getting bleu of around 0.15. and I was not handling the OOV words earlier. But currently working on some addition to this project. You can definitely checkout them out, if interested.
